version: '3.7'

services:
 jenkins:
  image: 'jenkinsci/blueocean'
  restart : unless-stopped
  user: root
  privileged: true
  ports:
   - '9090:8080'
  volumes:
   - '/home/ubuntu/docker/jenkins-data:/var/jenkins_home'
   - '/var/run/docker.sock:/var/run/docker.sock'
   - '$HOME:/home'
  container_name: 'jenkins'